# CODE IS GENERATED BY PRABESH SITAULA 


class Book:
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn
        self.available = True

    def __str__(self):
        availability = "Available" if self.available else "Not Available"
        return f"Title: {self.title}\nAuthor: {self.author}\nISBN: {self.isbn}\nAvailability: {availability}\n"


class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)
        print(f"Book '{book.title}' by {book.author} added to the library.")

    def remove_book(self, book):
        if book in self.books:
            self.books.remove(book)
            print(f"Book '{book.title}' by {book.author} removed from the library.")
        else:
            print("Book not found in the library.")

    def search_by_author(self, author):
        result = []
        for book in self.books:
            if book.author.lower() == author.lower():
                result.append(book)
        return result

    def search_by_title(self, title):
        result = []
        for book in self.books:
            if book.title.lower() == title.lower():
                result.append(book)
        return result


def main():
    library = Library()

    while True:
        print("\n---- Library Management System ----")
        print("1. Add Book")
        print("2. Remove Book")
        print("3. Search by Author")
        print("4. Search by Title")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")
        print("\n")

        if choice == "1":
            title = input("Enter the book title: ")
            author = input("Enter the book author: ")
            isbn = input("Enter the book ISBN: ")
            book = Book(title, author, isbn)
            library.add_book(book)

        elif choice == "2":
            title = input("Enter the book title: ")
            author = input("Enter the book author: ")
            books = library.search_by_title(title)
            matching_books = [b for b in books if b.author == author]
            if matching_books:
                if len(matching_books) == 1:
                    library.remove_book(matching_books[0])
                else:
                    print("Multiple books found. Please provide the ISBN of the book you want to remove.")
                    isbn = input("Enter the book ISBN: ")
                    for book in matching_books:
                        if book.isbn == isbn:
                            library.remove_book(book)
                            break
                    else:
                        print("Book not found in the library.")
            else:
                print("Book not found in the library.")

        elif choice == "3":
            author = input("Enter the author name: ")
            books = library.search_by_author(author)
            if books:
                print(f"Books by '{author}':")
                for book in books:
                    print(book)
            else:
                print("No books found by the given author.")

        elif choice == "4":
            title = input("Enter the book title: ")
            books = library.search_by_title(title)
            if books:
                print(f"Books with title '{title}':")
                for book in books:
                    print(book)
            else:
                print("No books found with the given title.")

        elif choice == "5":
            print("Exiting the program. Thank you!")
            break

        else:
            print("Invalid choice. Please enter a number from 1 to 5.")


if __name__ == "__main__":
    main()
